### PR TITLE
Hack to make X11 work

### PR DESCRIPTION
**Pull request by j4qfrost**
This is a lot less invasive than my previous pull requests. Feels like a hack though. I am checking against the OS which doesn't specifically block out X11, but seeing as how flutter uses X11 for linux, we shouldn't run into any issues.

### CODE REVIEW

**Comment by dvc94ch** [comment]
I see you're still experiencing an issue, at @csnewman also ran into it. Can you explain when and why it occurs?

**Comment by dvc94ch** [comment]
So as @csnewman suggested it looks like winit may not be generating an entered event on x11 if the window starts with the cursor already over it. The right way to fix this would be to make sure that an enter event is always generated.

**Comment by j4qfrost** [comment]
In my case, it looked like 2 entered events were being sent or X11 was handling entered events on its own, since the states.find check indicated that the device was already stored in the device map.

**Comment by dvc94ch** [comment]
also can you rebase and squash the changes?

`git reset HEAD~8 && git add . && git commit -m "hack to make x11 work" && git fetch upstream master && git rebase upstream/master && git push origin master -f`

we really need a proper fix so that we can merge it.

**Comment by csnewman** [comment]
I'm not sure this is the correct approach. We should check if the device is already added, and if so, don't send an additional add.

**Comment by j4qfrost** [comment]
I think the only way to properly check this is on the engine-side. Are either of you working on local engine build subcommands for cargo-flutter?

**Comment by csnewman** [comment]
Local engine builds? We shouldn't need to patch the actual flutter engine, the logic to prevent this error should be handled in flutter-rs (in the flutter-engine crate). As it is a bug to be sending two for sure.

**Comment by dvc94ch** [comment]
what I don't fully understand is why we are sending two entered events. is it a winit bug? but we can easily fix it on the flutter-rs side.

**Comment by csnewman** [comment]
Afaik it's a winit bug

**Comment by j4qfrost** [comment]
I made the Pointers index function return a bool to check whether the
device was newly added, and it doesn't help with the flutter engine check.
Is this a bug on our side or winit rs? I think what's happening is that
winit sends one event on its own then we send our event, which fails the
new device check.

Off topic: I figured being able to tinker with the engine would help
diagnose something like this, since we would be able to add printf's
internally. Is there a debugger option instead?

**Comment by dvc94ch** [comment]
Closing this for now

**Pull request closed without merging**
