### PR TITLE
Better threading

### PR DESCRIPTION
**Pull request by 999eagle**
This PR adds a custom task runner to eliminate the deprecated call to `__FlutterEngineFlushPendingTasksNow`. The task runner will let glfw wait indefinitely for window events if no tasks have been posted. This improves performance by polling glfw events less often. There's also a new function available to plugins that allows tasks to be posted to the render thread. Plugins can use this function to do full OpenGL rendering to the resource window.

I have also formatted the code and fixed some warnings.

### CODE REVIEW

**Comment by gliheng** [comment]
Wow, this is a huge improvement. Didn't notice this embedder api change. Do you have example how plugin can do OpenGL rendering?

**Comment by gliheng** [comment]
Why not just merge this into master?

**Comment by 999eagle** [comment]
I'm still working on implementing the default video player plugin that needs to render to OpenGL, so I don't have an example ready right now.

Well I started working on develop instead of master because that's what I thought was correct. If you want, I can of course merge the current develop branch into master.

**Comment by gliheng** [comment]
OK. This workflow is cool. Feature branch -> develop -> master, Once we merge into master, we make a release. Small fixed can go directly to develop.

Had pushed a few directly into master. My bad.

**Comment by gliheng** [comment]
Lots of conflicts when merging into master. Can you that PR to master please? I'll make a new develop branch.

**Comment by 999eagle** [comment]
Yeah, I just wrote on the Gitter channel about that. I'll resolve the conflicts in #76

**Pull request merged**
